version: '3.8'
services:
  calendar_icons:
    build: .
    container_name: calendar_icons
    volumes:
      # google credentials
      - type: bind
        source: .\creds
        target: /tmp/calendar_icons
      # for .env file
      - type: bind
        source: .
        target: /app
    env_file: .env
